name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v6
        with:
          go-version: "1.24"

      - name: Run Tests
        run: go test ./...

      - name: Run GolangCI-Lint
        uses: golangci/golangci-lint-action@v8