name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: user-service

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v6
        with:
          go-version-file: user-service/go.mod

      - name: Run Tests
        run: go test ./...

      - name: Run GolangCI-Lint
        uses: golangci/golangci-lint-action@v8
        with:
          working-directory: user-service

      - name: Build Docker Image
        run: docker build -t user-service .
