name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service:
          - api-gateway
          - product-service
          - user-service
          - cart-service
          - order-service
          - notification-service
          - fulfillment-service
          - analytics-service

    defaults:
      run:
        working-directory: ${{ matrix.service }}

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v6
        with:
          go-version-file: ${{ matrix.service }}/go.mod
          cache-dependency-path: ${{ matrix.service }}/go.sum

      - name: Sync and verify modules
        run: |
          go mod tidy
          go mod verify
          git diff --exit-code go.mod go.sum

      - name: Run tests
        run: go test ./...

      - name: Build
        run: go build -o server ./cmd/server

      - name: Run GolangCI-Lint
        uses: golangci/golangci-lint-action@v8
        with:
          working-directory: ${{ matrix.service }}
          skip-cache: true

      - name: Build Docker image
        run: docker build -t ${{ matrix.service }} .
